-- ============================================================
-- GARANTIZAR COLUMNAS EN TABLAS EXISTENTES
-- (Si la tabla ya existia de ejecucion parcial previa,
--  CREATE TABLE IF NOT EXISTS la omite, asi que agregamos
--  cada columna con ALTER TABLE ADD COLUMN IF NOT EXISTS)
-- ============================================================
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS nombre          TEXT;
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS direccion       TEXT;
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS ciudad          TEXT NOT NULL DEFAULT 'Ocotal';
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS departamento    TEXT NOT NULL DEFAULT 'Nueva Segovia';
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS pais            TEXT NOT NULL DEFAULT 'Nicaragua';
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS telefono_claro  TEXT;
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS telefono_tigo   TEXT;
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS correo          TEXT;
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS activo          BOOLEAN DEFAULT TRUE;
ALTER TABLE sucursales              ADD COLUMN IF NOT EXISTS actualizado_en  TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE perfiles                ADD COLUMN IF NOT EXISTS rol             rol_usuario DEFAULT 'cliente';
ALTER TABLE perfiles                ADD COLUMN IF NOT EXISTS nombre_completo TEXT;
ALTER TABLE perfiles                ADD COLUMN IF NOT EXISTS telefono        TEXT;
ALTER TABLE perfiles                ADD COLUMN IF NOT EXISTS url_avatar      TEXT;
ALTER TABLE perfiles                ADD COLUMN IF NOT EXISTS sucursal_id     UUID;
ALTER TABLE perfiles                ADD COLUMN IF NOT EXISTS activo          BOOLEAN DEFAULT TRUE;
ALTER TABLE perfiles                ADD COLUMN IF NOT EXISTS actualizado_en  TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE motorizados             ADD COLUMN IF NOT EXISTS perfil_id        UUID;
ALTER TABLE motorizados             ADD COLUMN IF NOT EXISTS tipo_vehiculo    tipo_vehiculo DEFAULT 'moto';
ALTER TABLE motorizados             ADD COLUMN IF NOT EXISTS placa            TEXT;
ALTER TABLE motorizados             ADD COLUMN IF NOT EXISTS ubicacion_actual GEOGRAPHY(Point, 4326);
ALTER TABLE motorizados             ADD COLUMN IF NOT EXISTS disponible       BOOLEAN DEFAULT TRUE;
ALTER TABLE motorizados             ADD COLUMN IF NOT EXISTS ordenes_activas  INT DEFAULT 0;
ALTER TABLE motorizados             ADD COLUMN IF NOT EXISTS sucursal_id      UUID;
ALTER TABLE motorizados             ADD COLUMN IF NOT EXISTS activo           BOOLEAN DEFAULT TRUE;
ALTER TABLE motorizados             ADD COLUMN IF NOT EXISTS actualizado_en   TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS tipo_servicio    tipo_servicio;
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS nombre_mostrar   TEXT;
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS descripcion      TEXT;
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS precio_base      DECIMAL(10,2) DEFAULT 40.00;
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS precio_por_parada DECIMAL(10,2) DEFAULT 40.00;
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS nombre_icono     TEXT;
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS precio_manual    BOOLEAN DEFAULT FALSE;
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS activo           BOOLEAN DEFAULT TRUE;
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS orden            INT DEFAULT 0;
ALTER TABLE catalogo_servicios      ADD COLUMN IF NOT EXISTS actualizado_en   TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS perfil_propietario_id UUID;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS nombre                TEXT;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS descripcion           TEXT;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS mision                TEXT;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS vision                TEXT;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS categoria             TEXT;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS url_logo              TEXT;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS url_portada           TEXT;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS telefono              TEXT;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS direccion             TEXT;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS ubicacion             GEOGRAPHY(Point, 4326);
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS tipo_plan             tipo_plan DEFAULT 'gratis';
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS suscripcion_activa    BOOLEAN DEFAULT TRUE;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS suscripcion_vence_en  TIMESTAMPTZ;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS activo                BOOLEAN DEFAULT TRUE;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS verificado            BOOLEAN DEFAULT FALSE;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS sucursal_id           UUID;
ALTER TABLE negocios                ADD COLUMN IF NOT EXISTS actualizado_en        TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS negocio_id     UUID;
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS nombre         TEXT;
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS descripcion    TEXT;
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS precio         DECIMAL(10,2);
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS url_imagen     TEXT;
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS categoria      TEXT;
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS inventario     INT;
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS disponible     BOOLEAN DEFAULT TRUE;
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS orden          INT DEFAULT 0;
ALTER TABLE productos_negocio       ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS perfil_cliente_id UUID;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS tipo_servicio     tipo_servicio;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS estado            estado_servicio DEFAULT 'pendiente';
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS direccion_origen  TEXT;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS ubicacion_origen  GEOGRAPHY(Point, 4326);
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS paradas           JSONB DEFAULT '[]'::jsonb;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS cantidad_paradas  INT DEFAULT 1;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS direccion_destino TEXT;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS ubicacion_destino GEOGRAPHY(Point, 4326);
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS precio_total      DECIMAL(10,2) DEFAULT 0;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS contenido_paquete TEXT;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS notas             TEXT;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS detalles_servicio JSONB DEFAULT '{}'::jsonb;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS canal_origen      canal_chat DEFAULT 'web';
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS negocio_id        UUID;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS sucursal_id       UUID;
ALTER TABLE solicitudes_servicio    ADD COLUMN IF NOT EXISTS actualizado_en    TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE asignaciones            ADD COLUMN IF NOT EXISTS solicitud_id     UUID;
ALTER TABLE asignaciones            ADD COLUMN IF NOT EXISTS motorizado_id    UUID;
ALTER TABLE asignaciones            ADD COLUMN IF NOT EXISTS estado           estado_servicio DEFAULT 'asignado';
ALTER TABLE asignaciones            ADD COLUMN IF NOT EXISTS asignado_en      TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE asignaciones            ADD COLUMN IF NOT EXISTS iniciado_en      TIMESTAMPTZ;
ALTER TABLE asignaciones            ADD COLUMN IF NOT EXISTS completado_en    TIMESTAMPTZ;
ALTER TABLE asignaciones            ADD COLUMN IF NOT EXISTS cancelado_en     TIMESTAMPTZ;
ALTER TABLE asignaciones            ADD COLUMN IF NOT EXISTS notas_motorizado TEXT;
ALTER TABLE asignaciones            ADD COLUMN IF NOT EXISTS actualizado_en   TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE ganancias               ADD COLUMN IF NOT EXISTS motorizado_id  UUID;
ALTER TABLE ganancias               ADD COLUMN IF NOT EXISTS asignacion_id  UUID;
ALTER TABLE ganancias               ADD COLUMN IF NOT EXISTS monto          DECIMAL(10,2);
ALTER TABLE ganancias               ADD COLUMN IF NOT EXISTS fecha_periodo  DATE DEFAULT CURRENT_DATE;
ALTER TABLE suscripciones           ADD COLUMN IF NOT EXISTS perfil_id      UUID;
ALTER TABLE suscripciones           ADD COLUMN IF NOT EXISTS estado         estado_suscripcion DEFAULT 'activa';
ALTER TABLE suscripciones           ADD COLUMN IF NOT EXISTS iniciado_en    TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE suscripciones           ADD COLUMN IF NOT EXISTS vence_en       TIMESTAMPTZ;
ALTER TABLE suscripciones           ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE suscripciones_negocio   ADD COLUMN IF NOT EXISTS negocio_id      UUID;
ALTER TABLE suscripciones_negocio   ADD COLUMN IF NOT EXISTS tipo_plan       tipo_plan DEFAULT 'gratis';
ALTER TABLE suscripciones_negocio   ADD COLUMN IF NOT EXISTS estado          estado_suscripcion DEFAULT 'activa';
ALTER TABLE suscripciones_negocio   ADD COLUMN IF NOT EXISTS precio_mensual  DECIMAL(10,2) DEFAULT 0;
ALTER TABLE suscripciones_negocio   ADD COLUMN IF NOT EXISTS iniciado_en     TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE suscripciones_negocio   ADD COLUMN IF NOT EXISTS vence_en        TIMESTAMPTZ;
ALTER TABLE suscripciones_negocio   ADD COLUMN IF NOT EXISTS actualizado_en  TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS titulo          TEXT;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS tipo_contenido  tipo_contenido;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS contenido       JSONB DEFAULT '{}'::jsonb;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS seccion_destino TEXT;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS fecha_inicio    TIMESTAMPTZ;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS fecha_fin       TIMESTAMPTZ;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS estado          estado_contenido DEFAULT 'borrador';
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS prioridad       INT DEFAULT 0;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS activo          BOOLEAN DEFAULT TRUE;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS creado_por      UUID;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS sucursal_id     UUID;
ALTER TABLE contenido_cms           ADD COLUMN IF NOT EXISTS actualizado_en  TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE testimonios             ADD COLUMN IF NOT EXISTS nombre_cliente TEXT;
ALTER TABLE testimonios             ADD COLUMN IF NOT EXISTS contenido      TEXT;
ALTER TABLE testimonios             ADD COLUMN IF NOT EXISTS calificacion   INT;
ALTER TABLE testimonios             ADD COLUMN IF NOT EXISTS url_avatar     TEXT;
ALTER TABLE testimonios             ADD COLUMN IF NOT EXISTS visible        BOOLEAN DEFAULT TRUE;
ALTER TABLE testimonios             ADD COLUMN IF NOT EXISTS orden          INT DEFAULT 0;
ALTER TABLE notificaciones          ADD COLUMN IF NOT EXISTS perfil_id UUID;
ALTER TABLE notificaciones          ADD COLUMN IF NOT EXISTS titulo    TEXT;
ALTER TABLE notificaciones          ADD COLUMN IF NOT EXISTS cuerpo    TEXT;
ALTER TABLE notificaciones          ADD COLUMN IF NOT EXISTS tipo      TEXT DEFAULT 'general';
ALTER TABLE notificaciones          ADD COLUMN IF NOT EXISTS datos     JSONB DEFAULT '{}'::jsonb;
ALTER TABLE notificaciones          ADD COLUMN IF NOT EXISTS leido     BOOLEAN DEFAULT FALSE;
ALTER TABLE sesiones_chat_ia        ADD COLUMN IF NOT EXISTS perfil_id             UUID;
ALTER TABLE sesiones_chat_ia        ADD COLUMN IF NOT EXISTS canal                 canal_chat DEFAULT 'web';
ALTER TABLE sesiones_chat_ia        ADD COLUMN IF NOT EXISTS telefono_whatsapp     TEXT;
ALTER TABLE sesiones_chat_ia        ADD COLUMN IF NOT EXISTS mensajes              JSONB DEFAULT '[]'::jsonb;
ALTER TABLE sesiones_chat_ia        ADD COLUMN IF NOT EXISTS estado                TEXT DEFAULT 'activa';
ALTER TABLE sesiones_chat_ia        ADD COLUMN IF NOT EXISTS solicitud_generada_id UUID;
ALTER TABLE sesiones_chat_ia        ADD COLUMN IF NOT EXISTS actualizado_en        TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE galeria                 ADD COLUMN IF NOT EXISTS url_imagen  TEXT;
ALTER TABLE galeria                 ADD COLUMN IF NOT EXISTS pie_foto    TEXT;
ALTER TABLE galeria                 ADD COLUMN IF NOT EXISTS categoria   TEXT;
ALTER TABLE galeria                 ADD COLUMN IF NOT EXISTS orden       INT DEFAULT 0;
ALTER TABLE galeria                 ADD COLUMN IF NOT EXISTS visible     BOOLEAN DEFAULT TRUE;
ALTER TABLE galeria                 ADD COLUMN IF NOT EXISTS sucursal_id UUID;
